import { Link } from 'react-router-dom';
import { useLanguage } from '../i18n';
import { ArrowLeft } from 'lucide-react';

export default function UserPolicyPage() {
  const { language } = useLanguage();

  return (
    <div className="min-h-screen bg-rakubun-bg text-rakubun-text">
      {/* Header */}
      <header className="border-b border-rakubun-border bg-rakubun-surface/80 backdrop-blur-xl sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center gap-4">
          <Link
            to="/"
            className="inline-flex items-center gap-2 text-sm text-rakubun-muted hover:text-rakubun-text transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            <span className="font-heading font-bold text-lg text-rakubun-text">RakuBun</span>
          </Link>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
        {language === 'ja' ? <UserPolicyJA /> : <UserPolicyEN />}
      </main>

      {/* Footer */}
      <footer className="border-t border-rakubun-border py-8">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-sm text-rakubun-muted">
            © {new Date().getFullYear()} RakuBun. All rights reserved.
          </p>
          <div className="flex items-center gap-6">
            <Link to="/privacy-policy" className="text-sm text-rakubun-muted hover:text-rakubun-text transition-colors">
              {language === 'ja' ? 'プライバシーポリシー' : 'Privacy Policy'}
            </Link>
            <Link to="/user-policy" className="text-sm text-rakubun-muted hover:text-rakubun-text transition-colors">
              {language === 'ja' ? '利用規約' : 'User Policy'}
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}

function UserPolicyEN() {
  return (
    <article className="prose prose-neutral dark:prose-invert max-w-none">
      <h1>User Policy (Terms of Service)</h1>
      <p className="text-rakubun-muted">Last updated: February 28, 2026</p>

      <p>
        Welcome to RakuBun. By accessing or using our website at <strong>rakubun.com</strong> and related services
        (the "Service"), you agree to be bound by these terms. If you do not agree, please do not use the Service.
      </p>

      <h2>1. Eligibility</h2>
      <p>
        You must be at least 16 years old to use the Service. By registering, you represent that you meet this
        requirement and that the information you provide is accurate and complete.
      </p>

      <h2>2. Account Responsibilities</h2>
      <ul>
        <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
        <li>You are responsible for all activity that occurs under your account.</li>
        <li>You must notify us immediately of any unauthorized use of your account.</li>
        <li>You may not share your account credentials with third parties.</li>
      </ul>

      <h2>3. Acceptable Use</h2>
      <p>You agree not to use the Service to:</p>
      <ul>
        <li>Publish content that is illegal, harmful, threatening, abusive, defamatory, or otherwise objectionable</li>
        <li>Infringe on intellectual property rights of others</li>
        <li>Distribute spam, malware, or phishing content</li>
        <li>Attempt to gain unauthorized access to the Service or other users' accounts</li>
        <li>Interfere with or disrupt the integrity or performance of the Service</li>
        <li>Scrape, crawl, or use automated means to access the Service beyond the provided API</li>
        <li>Use the Service to generate content that violates applicable laws or regulations</li>
      </ul>

      <h2>4. WordPress Integration</h2>
      <ul>
        <li>You authorize RakuBun to access your WordPress site using the credentials you provide.</li>
        <li>You are solely responsible for the content published to your WordPress site through the Service.</li>
        <li>You must have the right to publish content on the connected WordPress site.</li>
        <li>You may revoke access at any time by removing the Application Password from your WordPress site.</li>
      </ul>

      <h2>5. AI-Generated Content</h2>
      <ul>
        <li>Content generated by the Service is created using artificial intelligence and may require review before publication.</li>
        <li>You are responsible for reviewing and editing AI-generated content before it is published.</li>
        <li>RakuBun does not guarantee the accuracy, originality, or quality of AI-generated content.</li>
        <li>You retain ownership of content generated through the Service and published on your site.</li>
      </ul>

      <h2>6. Subscriptions &amp; Payments</h2>
      <ul>
        <li>Free tier: up to 5 articles per month at no charge.</li>
        <li>Paid plans are billed monthly or annually via Stripe.</li>
        <li>You may cancel your subscription at any time; access continues until the end of the current billing period.</li>
        <li>Refunds are handled on a case-by-case basis. Contact support for assistance.</li>
        <li>We reserve the right to change pricing with 30 days' notice.</li>
      </ul>

      <h2>7. Intellectual Property</h2>
      <ul>
        <li>The Service, including its design, code, and branding, is owned by RakuBun and protected by intellectual property laws.</li>
        <li>You retain ownership of your original content and data.</li>
        <li>You grant RakuBun a limited license to process your content solely for the purpose of providing the Service.</li>
      </ul>

      <h2>8. Service Availability</h2>
      <ul>
        <li>We strive to maintain high availability but do not guarantee uninterrupted access.</li>
        <li>We may perform maintenance or updates that temporarily affect availability.</li>
        <li>We reserve the right to modify, suspend, or discontinue any part of the Service with reasonable notice.</li>
      </ul>

      <h2>9. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, RakuBun shall not be liable for any indirect, incidental,
        special, consequential, or punitive damages, including but not limited to loss of profits, data, or
        business opportunities, arising from your use of the Service.
      </p>
      <p>
        Our total liability for any claim related to the Service shall not exceed the amount you paid us in the
        12 months preceding the claim.
      </p>

      <h2>10. Disclaimer of Warranties</h2>
      <p>
        The Service is provided "as is" and "as available" without warranties of any kind, either express or
        implied, including but not limited to implied warranties of merchantability, fitness for a particular
        purpose, and non-infringement.
      </p>

      <h2>11. Termination</h2>
      <ul>
        <li>You may terminate your account at any time through your account settings.</li>
        <li>We may suspend or terminate your account if you violate these terms.</li>
        <li>Upon termination, your data will be handled in accordance with our Privacy Policy.</li>
      </ul>

      <h2>12. Governing Law</h2>
      <p>
        These terms are governed by and construed in accordance with the laws of Japan. Any disputes arising
        from these terms shall be subject to the exclusive jurisdiction of the courts of Tokyo, Japan.
      </p>

      <h2>13. Changes to These Terms</h2>
      <p>
        We may update these terms from time to time. We will notify you of material changes by posting the
        updated terms on this page. Continued use of the Service after changes constitutes acceptance of the
        updated terms.
      </p>

      <h2>14. Contact Us</h2>
      <p>
        If you have questions about these terms, please contact us at{' '}
        <a href="mailto:support@rakubun.com">support@rakubun.com</a>.
      </p>
    </article>
  );
}

function UserPolicyJA() {
  return (
    <article className="prose prose-neutral dark:prose-invert max-w-none">
      <h1>利用規約</h1>
      <p className="text-rakubun-muted">最終更新日：2026年2月28日</p>

      <p>
        RakuBunへようこそ。<strong>rakubun.com</strong> および関連サービス（以下「本サービス」）にアクセスまたは使用することにより、
        本規約に同意したものとみなされます。同意いただけない場合は、本サービスをご利用にならないでください。
      </p>

      <h2>1. 利用資格</h2>
      <p>
        本サービスの利用には16歳以上である必要があります。
        ご登録により、この要件を満たしていること、および提供する情報が正確かつ完全であることを表明するものとします。
      </p>

      <h2>2. アカウントの責任</h2>
      <ul>
        <li>アカウント認証情報の機密性を維持する責任があります。</li>
        <li>アカウント上で発生するすべての活動に対して責任を負います。</li>
        <li>アカウントの不正使用があった場合は、直ちに当社に通知してください。</li>
        <li>アカウント認証情報を第三者と共有することはできません。</li>
      </ul>

      <h2>3. 許容される使用</h2>
      <p>本サービスを以下の目的で使用しないことに同意するものとします：</p>
      <ul>
        <li>違法、有害、脅迫的、虐待的、名誉毀損的、またはその他好ましくないコンテンツの公開</li>
        <li>他者の知的財産権の侵害</li>
        <li>スパム、マルウェア、フィッシングコンテンツの配布</li>
        <li>本サービスまたは他のユーザーのアカウントへの不正アクセスの試み</li>
        <li>本サービスの完全性またはパフォーマンスへの干渉や妨害</li>
        <li>提供されたAPI以外の自動手段によるサービスへのアクセス</li>
        <li>適用法令に違反するコンテンツの生成</li>
      </ul>

      <h2>4. WordPress連携</h2>
      <ul>
        <li>提供された認証情報を使用してWordPressサイトにアクセスすることをRakuBunに許可するものとします。</li>
        <li>本サービスを通じてWordPressサイトに公開されるコンテンツについて、お客様が単独で責任を負います。</li>
        <li>接続されたWordPressサイトにコンテンツを公開する権利を有している必要があります。</li>
        <li>WordPressサイトからアプリケーションパスワードを削除することで、いつでもアクセスを取り消すことができます。</li>
      </ul>

      <h2>5. AI生成コンテンツ</h2>
      <ul>
        <li>本サービスで生成されるコンテンツは人工知能を使用して作成されており、公開前に確認が必要な場合があります。</li>
        <li>AI生成コンテンツは公開前に確認・編集する責任があります。</li>
        <li>RakuBunはAI生成コンテンツの正確性、独自性、品質を保証しません。</li>
        <li>本サービスを通じて生成され、サイトに公開されたコンテンツの所有権はお客様に帰属します。</li>
      </ul>

      <h2>6. サブスクリプションと支払い</h2>
      <ul>
        <li>無料プラン：月5記事まで無料。</li>
        <li>有料プランはStripeを通じて月額または年額で請求されます。</li>
        <li>サブスクリプションはいつでもキャンセルでき、現在の請求期間の終了までアクセスが継続されます。</li>
        <li>返金はケースバイケースで対応します。サポートにお問い合わせください。</li>
        <li>30日前の通知をもって価格を変更する権利を留保します。</li>
      </ul>

      <h2>7. 知的財産</h2>
      <ul>
        <li>デザイン、コード、ブランディングを含む本サービスはRakuBunが所有し、知的財産法により保護されています。</li>
        <li>お客様のオリジナルコンテンツおよびデータの所有権はお客様に帰属します。</li>
        <li>本サービスの提供を目的として、お客様のコンテンツを処理するための限定的なライセンスをRakuBunに付与するものとします。</li>
      </ul>

      <h2>8. サービスの可用性</h2>
      <ul>
        <li>高い可用性の維持に努めていますが、中断のないアクセスを保証するものではありません。</li>
        <li>可用性に一時的に影響するメンテナンスやアップデートを行う場合があります。</li>
        <li>合理的な通知をもって、本サービスの一部を変更、停止、または廃止する権利を留保します。</li>
      </ul>

      <h2>9. 責任の制限</h2>
      <p>
        法律で許容される最大限の範囲において、RakuBunは、本サービスの使用に起因する間接的、偶発的、
        特別、結果的、または懲罰的損害（利益、データ、またはビジネス機会の損失を含むがこれに限定されない）
        について責任を負わないものとします。
      </p>
      <p>
        本サービスに関連する請求に対する当社の総責任額は、請求に先立つ12か月間にお客様が当社に支払った金額を超えないものとします。
      </p>

      <h2>10. 保証の免責</h2>
      <p>
        本サービスは「現状のまま」「利用可能な状態で」提供され、商品性、特定目的への適合性、
        非侵害の黙示の保証を含むがこれに限定されない、明示または黙示のいかなる種類の保証もありません。
      </p>

      <h2>11. 終了</h2>
      <ul>
        <li>アカウント設定からいつでもアカウントを終了できます。</li>
        <li>本規約に違反した場合、アカウントを停止または終了する場合があります。</li>
        <li>終了時のデータはプライバシーポリシーに従って処理されます。</li>
      </ul>

      <h2>12. 準拠法</h2>
      <p>
        本規約は日本法に準拠し、同法に従って解釈されます。
        本規約に起因する紛争は、東京地方裁判所の専属管轄に服するものとします。
      </p>

      <h2>13. 規約の変更</h2>
      <p>
        本規約は随時更新される場合があります。重要な変更については、このページに更新版を掲載してお知らせします。
        変更後も本サービスを継続して使用することにより、更新された規約に同意したものとみなされます。
      </p>

      <h2>14. お問い合わせ</h2>
      <p>
        本規約に関するご質問は、
        <a href="mailto:support@rakubun.com">support@rakubun.com</a> までお問い合わせください。
      </p>
    </article>
  );
}
